---
title: "Gold Minning"
author: "Fantasy Football Analytics"
date: "Friday, October 31, 2014"
output: html_document
---

```{r, echo=FALSE,message=FALSE,results='hide',warning=FALSE}
require(data.table)
require(ggplot2)
require(RColorBrewer)
require(knitr)
require(seqinr)
require(mclust)
load("E:/FFA/GoldMining/ffa_wr.RData")

ffa<-ffa[min_rank<36]

sstat <- function(x){
  return(list("Lowest Projection"=min(x),"Highest Projection"=max(x),
              "Mean Projection" = mean(x),"Standard Deviation"=sd(x), "Median Projection"=median(x)))
         }
h.l <- function(x){tryCatch({
  wilcox.test(x,na.action="na.exclude",conf.int=TRUE)},
  error=function(e){return(list(estimate=median(x),conf.int=c(median(x)-sd(x),median(x)+sd(x))))})
}

htests<-ffa[,list(ppr_mean=mean(ppr_fpts),std_mean=mean(std_fpts),
                  ppr_min=min(ppr_fpts),ppr_max=max(ppr_fpts),
                  ppr_ave_rank=mean(ppr_rank), std_ave_rank=mean(std_rank),
                  ppr_h.l=list(h.l(ppr_fpts)),std_h.l=list(h.l(std_fpts))),by=name]
htests[,c("ppr_pm","ppr_pm_l","ppr_pm_h"):=list(vapply(ppr_h.l,function(x){x$estimate},double(1)),
                                    vapply(ppr_h.l,function(x){x$conf.int[1]},double(1)),
                                    vapply(ppr_h.l,function(x){x$conf.int[2]},double(1)))]
htests[,c("std_pm","std_pm_l","std_pm_h"):=list(vapply(std_h.l,function(x){x$estimate},double(1)),
                                    vapply(std_h.l,function(x){x$conf.int[1]},double(1)),
                                    vapply(std_h.l,function(x){x$conf.int[2]},double(1)))]

#clustering based on means.
htests[,c("ppr_tier","std_tier"):=list(Mclust(ppr_mean, G=7)$classification,Mclust(std_mean,G=7)$classification)]

htests[,c("ppr_h.l","std_h.l"):=NULL]
htests[order(-ppr_pm),ppr_rank:=1:.N]
```

This is an example of the sort of work product or arcticle we can produce automatically each week.  We can be creative about the text generation, which will take some work, but for the most part we should let the statistics do the work.

These are stats for week `r next_week`.

```{r,echo=FALSE,fig.height=10}
#graphing
#geom_point(size=3)+
ggplot(htests, aes(x=ppr_pm, y=ppr_rank, color=factor(ppr_tier))) +
  geom_errorbarh(aes(xmin=ppr_pm_l,xmax=ppr_pm_h),height=.3)+
  geom_point(size=5,color="white")+
  geom_text(aes(x=ppr_pm,label=round(ppr_pm,0)),size=3)+
  geom_text(aes(x=ppr_pm_h, label=name, hjust=-0.2, angle=(0), size=1))+
  theme(
    plot.background = element_blank()
    ,panel.grid.major = element_blank()
    ,panel.grid.minor = element_blank()
    ,panel.border = element_blank()
    ,panel.background = element_blank()
    ,legend.position = "none"
  ) + scale_y_reverse()+
  ylab("Average Rank") + xlab("Average FPTS Projection") +
  labs(title = paste("Week ", next_week, " WRs Uncertainty", sep="")) +
  coord_cartesian(xlim =c(0,(max(htests$ppr_pm_h)+10))) 

```

## Top Recievers - Standard Scoring leagues
```{r,echo=FALSE, results='asis', message=FALSE,warning=FALSE}
kable(ffa[order(std_ave_rank)][,c(sstat(std_fpts),list("Average Rank"=mean(ppr_rank))),
          by=name][1:30])
```

## Top Recievers - PPR leagues
```{r,echo=FALSE, results='asis'}
kable(ffa[order(ppr_ave_rank)][,c(sstat(ppr_fpts),list("Average Rank"=mean(ppr_rank))),
          by=name][1:30])
```


